defmodule Storybook.Introduction do
  use PhoenixStorybook.Story, :page

  @version Mix.Project.config()[:version]
  @components DemoWeb.CoreComponents.__dog_components__()
  @component_count map_size(@components)
  @category_count @components
                  |> Enum.map(fn {_name, info} -> info[:type] end)
                  |> Enum.uniq()
                  |> length()

  def render(assigns) do
    assigns =
      assigns
      |> assign(:version, @version)
      |> assign(:component_count, @component_count)
      |> assign(:category_count, @category_count)

    ~H"""
    <div class="psb-welcome-page">
      <p>
        Doggo is a headless component library for Phoenix LiveView. It defines
        the markup, the ARIA attributes, and the interactive behaviour, but it
        doesn't package any CSS. However, all components have example styles
        that are used in this storybook, and you can base your own styles on
        them.
      </p>
      <p>
        The components are generated by macros. The demo storybook shows all
        components with their default options. Component names, base classes and
        modifier attributes can be overridden in your own application.
      </p>
      <p>
        Not all components are stable yet. The build macro documentation and
        the documentation of the generated component include a maturity note.
      </p>
      <p>
        This storybook covers {@component_count} components in {@category_count} categories.
        It was compiled with Doggo {@version}.
      </p>

      <h2>Resources</h2>
      <ul>
        <li>
          <a href="https://github.com/woylie/doggo" target="_blank">
            Github repository
          </a>
        </li>
        <li>
          <a href="https://hexdocs.pm/doggo/readme.html" target="_blank">
            Installation and usage
          </a>
        </li>
        <li>
          <a href="https://hexdocs.pm/doggo/Doggo.Components.html" target="_blank">
            Components documentation
          </a>
        </li>
        <li>
          <a
            href="https://hexdocs.pm/doggo/Mix.Tasks.Dog.Gen.Stories.html"
            target="_blank"
          >
            Story generator task
          </a>
        </li>
        <li>
          <a
            href="https://github.com/woylie/doggo/tree/main/assets/css"
            target="_blank"
          >
            Example CSS
          </a>
        </li>
        <li>
          <a
            href="https://github.com/woylie/doggo/tree/main/test/fixtures"
            target="_blank"
          >
            Markup fixtures
          </a>
        </li>
      </ul>
    </div>
    """
  end
end
