defmodule DemoWeb.CoreComponents do
  use Doggo.Components
  use Phoenix.Component

  accordion(
    modifiers: [variant: [values: ["primary", "secondary"], default: "primary"]]
  )

  action_bar()
  alert()
  alert_dialog()
  app_bar()
  avatar()
  badge()
  bottom_navigation()
  box(modifiers: [size: [values: ["normal", "narrow"], default: "normal"]])
  breadcrumb()
  button()
  button_link()
  callout()
  card()
  carousel()
  cluster()
  combobox()
  date()
  datetime()
  disclosure_button()
  drawer()
  fab()
  fallback()
  field_description_builder()
  field_group_builder()
  frame_builder()
  icon()
  icon_sprite()
  image()
  menu()
  menu_bar()
  menu_button()
  menu_group()
  menu_item()
  menu_item_checkbox()
  menu_item_radio_group()
  modal()
  navbar()
  navbar_items()
  page_header()
  property_list()
  radio_group()
  skeleton()
  split_pane()
  stack()
  steps()
  switch()
  tab_navigation()
  table()
  tabs(modifiers: [size: [values: ["normal", "narrow"], default: "normal"]])
  tag()
  time()

  toggle_button(
    modifiers: [variant: [values: ["primary", "secondary"], default: "primary"]]
  )

  toolbar()
  tooltip()
  tree()
  tree_item()
  vertical_nav()
  vertical_nav_nested()
  vertical_nav_section()
end
